import type {
  IFarmer,
  IFarmerDGResponse,
  IFarmerRegistration,
} from "@/interfaces/farmers";
import $http from "@/plugins/axios";
import type { AxiosError } from "axios";
import { defineStore } from "pinia";

export const useFarmersStore = defineStore({
  id: "farmers",
  state: () => ({
    farmers: [
      {
        id: 250,
        company_id: "string",
        version: null,
        created_on: null,
        created_by: null,
        last_modified_on: null,
        last_modified_by: null,
        farmer_code: "FC-JJIZYBVJ7PWLRUSM",
        sale_agent_code: "string",
        id_no: "24446168",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "+254726339911",
        full_names: "string",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "REGISTERED",
        activation_stage: "SELF_REGISTRATION",
        deposit_limit: 250000,
        loan_limit: 0,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 0,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 333151,
        login_attempts: 0,
        new: false,
      },
      {
        id: 256,
        company_id: "string",
        version: null,
        created_on: null,
        created_by: null,
        last_modified_on: null,
        last_modified_by: null,
        farmer_code: "FC-WUMPWDP5AATKOURP",
        sale_agent_code: "999",
        id_no: "26446168",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "+254726339982",
        full_names: "string",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "REGISTERED",
        activation_stage: "SELF_REGISTRATION",
        deposit_limit: 250000,
        loan_limit: 0,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 1,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 229544,
        login_attempts: 0,
        new: false,
      },
      {
        id: 259,
        company_id: "string",
        version: null,
        created_on: null,
        created_by: null,
        last_modified_on: null,
        last_modified_by: null,
        farmer_code: "FC-ESTDPNZY12WET1FJ",
        sale_agent_code: "string",
        id_no: "27446168",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "+254708650590",
        full_names: "string",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "PENDING_REGISTRATION",
        activation_stage: "PENDING_REGISTRATION",
        deposit_limit: 0,
        loan_limit: 0,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 0,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 0,
        login_attempts: 0,
        new: false,
      },
      {
        id: 270,
        company_id: "string",
        version: null,
        created_on: null,
        created_by: null,
        last_modified_on: null,
        last_modified_by: null,
        farmer_code: "FC-DHZKYIGAZLLRZLQS",
        sale_agent_code: "1234",
        id_no: "12345678",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "254741987616",
        full_names: "Mary Otieno",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "REGISTERED",
        activation_stage: "SELF_REGISTRATION",
        deposit_limit: 250000,
        loan_limit: 0,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 0,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 241212,
        login_attempts: 0,
        new: false,
      },
      {
        id: 288,
        company_id: "string",
        version: 1,
        created_on: "2022-05-17T06:26:54.893950Z",
        created_by: "string",
        last_modified_on: "2022-05-17T06:27:48.403458Z",
        last_modified_by: "string",
        farmer_code: "FC-2YGHGMDFSCK1FL6A",
        sale_agent_code: "1234",
        id_no: "32711464",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "0708321651",
        full_names: "Mary Otieno",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "REGISTERED",
        activation_stage: "SELF_REGISTRATION",
        deposit_limit: 250000,
        loan_limit: 100000,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 0,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 3445,
        login_attempts: 0,
        new: false,
      },
      {
        id: 291,
        company_id: "string",
        version: 0,
        created_on: "2022-05-17T06:43:27.707403Z",
        created_by: "string",
        last_modified_on: "2022-05-17T06:43:27.707403Z",
        last_modified_by: "string",
        farmer_code: "FC-8QDNWW6UG1BM9QPR",
        sale_agent_code: "string",
        id_no: "12345679",
        county: "string",
        ward: "string",
        value_chaim: "string",
        farm_size: "string",
        photo: "string",
        signature: "string",
        additional_fields: "string",
        phone_number: "+254741987616",
        full_names: "Grace Gitonga",
        farmer_id: "string",
        payment_method: "MPESA",
        account_number: "string",
        account_name: "string",
        status: "PENDING_REGISTRATION",
        activation_stage: "PENDING_REGISTRATION",
        deposit_limit: 0,
        loan_limit: 0,
        email_validation: 0,
        crb_validation: 0,
        phone_number_validation: 0,
        phone_number_ownership_validation: 0,
        iprs_validation: 0,
        imsi_validation: 0,
        nip: 0,
        login_attempts: 0,
        new: false,
      },
    ],
    farmer: {
      id: 288,
      company_id: "string",
      version: 1,
      created_on: "2022-05-17T06:26:54.893950Z",
      created_by: "string",
      last_modified_on: "2022-05-17T06:27:48.403458Z",
      last_modified_by: "string",
      farmer_code: "FC-2YGHGMDFSCK1FL6A",
      sale_agent_code: "1234",
      id_no: "32711464",
      county: "string",
      ward: "string",
      value_chaim: "string",
      farm_size: "string",
      photo: "string",
      signature: "string",
      additional_fields: "string",
      phone_number: "0708321651",
      full_names: "Mary Otieno",
      farmer_id: "string",
      payment_method: "MPESA",
      account_number: "string",
      account_name: "string",
      status: "REGISTERED",
      activation_stage: "SELF_REGISTRATION",
      deposit_limit: 250000,
      loan_limit: 100000,
      email_validation: 0,
      crb_validation: 0,
      phone_number_validation: 0,
      phone_number_ownership_validation: 0,
      iprs_validation: 0,
      imsi_validation: 0,
      nip: 3445,
      login_attempts: 0,
      new: true,
    },
    farmerDeposits: {
      content: [
        {
          id: 342,
          company_id: null,
          version: 0,
          created_on: "2022-05-17T10:00:26.845638Z",
          created_by: null,
          last_modified_on: "2022-05-17T10:00:26.845638Z",
          last_modified_by: null,
          transaction_code: "PYT-HH1ZJBC3CRSJ",
          description: null,
          farmer: {
            id: 288,
            company_id: "string",
            version: 1,
            created_on: "2022-05-17T06:26:54.893950Z",
            created_by: "string",
            last_modified_on: "2022-05-17T06:27:48.403458Z",
            last_modified_by: "string",
            farmer_code: "FC-2YGHGMDFSCK1FL6A",
            sale_agent_code: "1234",
            id_no: "32711464",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "0708321651",
            full_names: "Mary Otieno",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 100000,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 3445,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
      ],
      pageable: {
        sort: {
          sorted: false,
          empty: true,
          unsorted: true,
        },
        page_size: 20,
        page_number: 0,
        offset: 0,
        paged: true,
        unpaged: false,
      },
      total_pages: 1,
      total_elements: 1,
      last: true,
      number: 0,
      size: 20,
      number_of_elements: 1,
      sort: {
        sorted: false,
        empty: true,
        unsorted: true,
      },
      first: true,
      empty: false,
    },

    farmerLoanPayments: {
      content: [
        {
          id: 346,
          company_id: null,
          version: 0,
          created_on: "2022-05-17T10:44:10.470349Z",
          created_by: null,
          last_modified_on: "2022-05-17T10:44:10.470349Z",
          last_modified_by: null,
          transaction_code: "RMT-S1QESW71PXXH6D3W",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 1000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 354,
          company_id: null,
          version: 0,
          created_on: "2022-05-19T16:57:17.110714Z",
          created_by: null,
          last_modified_on: "2022-05-19T16:57:17.110714Z",
          last_modified_by: null,
          transaction_code: "RMT-DONNPCFCFZZT0BJO",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 100,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 356,
          company_id: null,
          version: 0,
          created_on: "2022-05-19T16:58:26.584230Z",
          created_by: null,
          last_modified_on: "2022-05-19T16:58:26.584230Z",
          last_modified_by: null,
          transaction_code: "RMT-Z8Z0OBEYNLBO0DDZ",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 100,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 358,
          company_id: null,
          version: 0,
          created_on: "2022-05-19T16:58:33.796063Z",
          created_by: null,
          last_modified_on: "2022-05-19T16:58:33.796063Z",
          last_modified_by: null,
          transaction_code: "RMT-GAKO5FKBCNC7DMGI",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 100,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 364,
          company_id: null,
          version: 0,
          created_on: "2022-05-19T17:03:31.199741Z",
          created_by: null,
          last_modified_on: "2022-05-19T17:03:31.199741Z",
          last_modified_by: null,
          transaction_code: "RMT-IDSRAEWDE3MITTVT",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 100,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 375,
          company_id: null,
          version: 0,
          created_on: "2022-05-20T15:26:57.498523Z",
          created_by: null,
          last_modified_on: "2022-05-20T15:26:57.498523Z",
          last_modified_by: null,
          transaction_code: "RMT-1RGVF1THPPEX5GIR",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 100,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 427,
          company_id: null,
          version: 0,
          created_on: "2022-05-21T10:08:03.019552Z",
          created_by: null,
          last_modified_on: "2022-05-21T10:08:03.019552Z",
          last_modified_by: null,
          transaction_code: "RMT-RNQESNEIEXR63R5P",
          description: null,
          farmer: {
            id: 412,
            company_id: "string",
            version: 1,
            created_on: "2022-05-21T09:14:00.588609Z",
            created_by: "string",
            last_modified_on: "2022-05-21T09:15:47.478711Z",
            last_modified_by: "string",
            farmer_code: "FC-0ZK9DQNZ4A7ER4A1",
            sale_agent_code: "1234",
            id_no: "27446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254722604072",
            full_names: "Peter Mayoye",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "+254722604072",
            account_name: "Peter Mayoye",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 61744,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 10000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 457,
          company_id: null,
          version: 0,
          created_on: "2022-05-21T18:50:34.224362Z",
          created_by: null,
          last_modified_on: "2022-05-21T18:50:34.224362Z",
          last_modified_by: null,
          transaction_code: "RMT-AZTNQYHRT30ZYS7B",
          description: null,
          farmer: {
            id: 444,
            company_id: "string",
            version: 2,
            created_on: "2022-05-21T16:53:29.521090Z",
            created_by: "string",
            last_modified_on: "2022-05-21T17:04:24.403410Z",
            last_modified_by: "string",
            farmer_code: "FC-U8EEKMI0IAOMQN4L",
            sale_agent_code: "111",
            id_no: "22222222",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254736541885",
            full_names: "Edwin Kitur",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "+254736541885",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 169921,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 3000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 580,
          company_id: null,
          version: 0,
          created_on: "2022-05-24T18:20:14.968926Z",
          created_by: null,
          last_modified_on: "2022-05-24T18:20:14.968926Z",
          last_modified_by: null,
          transaction_code: "RMT-IJKUMQCEKLKTEA4V",
          description: null,
          farmer: {
            id: 502,
            company_id: "string",
            version: 1,
            created_on: "2022-05-24T11:37:17.417509Z",
            created_by: "string",
            last_modified_on: "2022-05-24T11:39:40.748512Z",
            last_modified_by: "string",
            farmer_code: "FC-ULZQLCXDXOFUG69M",
            sale_agent_code: "1234",
            id_no: "40382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254706915605",
            full_names: "Emmanuel Muchiri",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "Emmanuel Muchiri",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 0,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 577980,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 5000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 629,
          company_id: null,
          version: 0,
          created_on: "2022-05-25T18:26:36.231737Z",
          created_by: null,
          last_modified_on: "2022-05-25T18:26:36.231737Z",
          last_modified_by: null,
          transaction_code: "RMT-WP393XNT1RAHPJFV",
          description: null,
          farmer: {
            id: 444,
            company_id: "string",
            version: 2,
            created_on: "2022-05-21T16:53:29.521090Z",
            created_by: "string",
            last_modified_on: "2022-05-21T17:04:24.403410Z",
            last_modified_by: "string",
            farmer_code: "FC-U8EEKMI0IAOMQN4L",
            sale_agent_code: "111",
            id_no: "22222222",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254736541885",
            full_names: "Edwin Kitur",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "+254736541885",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 169921,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 1000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
        {
          id: 657,
          company_id: null,
          version: 0,
          created_on: "2022-05-27T08:22:20.056443Z",
          created_by: null,
          last_modified_on: "2022-05-27T08:22:20.056443Z",
          last_modified_by: null,
          transaction_code: "RMT-1GDO5QZAKNSSQE64",
          description: null,
          farmer: {
            id: 634,
            company_id: "string",
            version: 1,
            created_on: "2022-05-27T08:06:16.105307Z",
            created_by: "string",
            last_modified_on: "2022-05-27T08:14:47.422291Z",
            last_modified_by: "string",
            farmer_code: "FC-BUQEWAFUJIGODJCZ",
            sale_agent_code: "1234",
            id_no: "70382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254712042033",
            full_names: "Kiprono Tanui",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 60467,
            login_attempts: 0,
            new: false,
          },
          debit: null,
          credit: 5000,
          transaction_type: "LOAN_REPAYMENT",
          account_type: "LOAN_ACCOUNT",
          new: false,
        },
      ],
      pageable: {
        sort: {
          sorted: false,
          empty: true,
          unsorted: true,
        },
        page_size: 20,
        page_number: 0,
        offset: 0,
        paged: true,
        unpaged: false,
      },
      total_pages: 1,
      total_elements: 11,
      last: true,
      number: 0,
      size: 20,
      number_of_elements: 11,
      sort: {
        sorted: false,
        empty: true,
        unsorted: true,
      },
      first: true,
      empty: false,
    },

    farmerAccount: {},
    farmerAccountBalance: 10000,
    isLoading: false,
  }),
  getters: {
    getFarmers: (state) => state.farmers,
    getFarmerCount: (state) => state.farmers.length,
    getFarmerAccountBalance: (state) => state.farmerAccountBalance,
    getFarmerDeposits: (state) => state.farmerDeposits.content,
    getFarmerDepositCount: (state) => state.farmerDeposits.total_elements,
    getFarmerLoanPayments: (state) => state.farmerLoanPayments.content,
    getFarmerPaymentsCount: (state) => state.farmerLoanPayments.total_elements,
    getFarmer: (state) => state.farmer,
    getLoading: (state) => state.isLoading,
  },
  actions: {
    async fetchFarmerAccount(payload) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmer-account?includeClosed=${payload.includeClosed}&q=${payload.q}&type=${payload.type}&page=${payload.page}&pageSize=${payload.pageSize}`,
        });
        this.farmerAccount = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmerAccountBalance(farmerId: number) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmer-account/${farmerId}/balance`,
        });
        this.farmerAccountBalance = response.data.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmers() {
      try {
        const response = await $http.Api({
          method: "GET",
          url: "/farmers",
        });
        this.farmers = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmer(farmerId: number) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmers/${farmerId}`,
        });
        this.farmer = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmerbyPhone(phoneNumber: number) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmers/get-farmer-by-phone-number/${phoneNumber}`,
        });
        this.farmer = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmerbyIdNumber(idNumber: string) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmers/get-farmer-by-id-no/${idNumber}`,
        });
        this.farmer = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchFarmerDeposits(farmerCode: string) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/farmer-account?farmerCode=${farmerCode}&transactionType=DEPOSIT`,
        });
        this.farmerDeposits = response.data.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async registerFarmer(payload: IFarmerRegistration) {
      try {
        const response = await $http.Api({
          method: "POST",
          url: `/farmers/register`,
          data: payload,
        });
        console.log("registered farmer", response.data);
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async updateFarmer(payload: IFarmer) {
      try {
        const response = await $http.Api({
          method: "PUT",
          url: "/farmers",
          data: payload,
        });
        console.log("registered farmer", response.data);
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async deleteFarmer(farmerId: number) {
      try {
        const response = await $http.Api({
          method: "DELETE",
          url: `/farmers/${farmerId}`,
        });
        console.log("deleted farmer", response.data);
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async setFarmer(farmerItem: IFarmerDGResponse) {
      try {
        console.log("setting farmer", farmerItem.id);
        this.farmer = farmerItem;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },
  },
});
