import type { IFarmer, IFarmerRegistration } from "@/interfaces/farmers";
import $http from "@/plugins/axios";
import type { AxiosError } from "axios";
import { defineStore } from "pinia";

export const useTransactionStore = defineStore({
  id: "transactions",
  state: () => ({
    deposits: {
      content: [
        {
          id: 341,
          company_id: null,
          version: 0,
          created_on: "2022-05-17T09:57:33.248429Z",
          created_by: null,
          last_modified_on: "2022-05-17T09:57:33.248429Z",
          last_modified_by: null,
          transaction_code: "PYT-XHSMDBU3NPSG",
          description: null,
          farmer: {
            id: 256,
            company_id: "string",
            version: null,
            created_on: null,
            created_by: null,
            last_modified_on: null,
            last_modified_by: null,
            farmer_code: "FC-WUMPWDP5AATKOURP",
            sale_agent_code: "999",
            id_no: "26446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254726339982",
            full_names: "string",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 229544,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 342,
          company_id: null,
          version: 0,
          created_on: "2022-05-17T10:00:26.845638Z",
          created_by: null,
          last_modified_on: "2022-05-17T10:00:26.845638Z",
          last_modified_by: null,
          transaction_code: "PYT-HH1ZJBC3CRSJ",
          description: null,
          farmer: {
            id: 288,
            company_id: "string",
            version: 1,
            created_on: "2022-05-17T06:26:54.893950Z",
            created_by: "string",
            last_modified_on: "2022-05-17T06:27:48.403458Z",
            last_modified_by: "string",
            farmer_code: "FC-2YGHGMDFSCK1FL6A",
            sale_agent_code: "1234",
            id_no: "32711464",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "0708321651",
            full_names: "Mary Otieno",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 100000,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 3445,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 425,
          company_id: null,
          version: 0,
          created_on: "2022-05-21T09:57:04.476380Z",
          created_by: null,
          last_modified_on: "2022-05-21T09:57:04.476380Z",
          last_modified_by: null,
          transaction_code: "PYT-I43KYIUKEEOP",
          description: null,
          farmer: {
            id: 412,
            company_id: "string",
            version: 1,
            created_on: "2022-05-21T09:14:00.588609Z",
            created_by: "string",
            last_modified_on: "2022-05-21T09:15:47.478711Z",
            last_modified_by: "string",
            farmer_code: "FC-0ZK9DQNZ4A7ER4A1",
            sale_agent_code: "1234",
            id_no: "27446168",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254722604072",
            full_names: "Peter Mayoye",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "+254722604072",
            account_name: "Peter Mayoye",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 61744,
            login_attempts: 0,
            new: false,
          },
          debit: 15000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 428,
          company_id: null,
          version: 0,
          created_on: "2022-05-21T18:43:25.886938Z",
          created_by: null,
          last_modified_on: "2022-05-21T18:43:25.886938Z",
          last_modified_by: null,
          transaction_code: "PYT-PNDB8HHYCWFW",
          description: null,
          farmer: {
            id: 444,
            company_id: "string",
            version: 2,
            created_on: "2022-05-21T16:53:29.521090Z",
            created_by: "string",
            last_modified_on: "2022-05-21T17:04:24.403410Z",
            last_modified_by: "string",
            farmer_code: "FC-U8EEKMI0IAOMQN4L",
            sale_agent_code: "111",
            id_no: "22222222",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "+254736541885",
            full_names: "Edwin Kitur",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "+254736541885",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 169921,
            login_attempts: 0,
            new: false,
          },
          debit: 5000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 523,
          company_id: null,
          version: 0,
          created_on: "2022-05-24T14:15:13.628211Z",
          created_by: null,
          last_modified_on: "2022-05-24T14:15:13.628211Z",
          last_modified_by: null,
          transaction_code: "PYT-HNET3JCMDO5K",
          description: null,
          farmer: {
            id: 502,
            company_id: "string",
            version: 1,
            created_on: "2022-05-24T11:37:17.417509Z",
            created_by: "string",
            last_modified_on: "2022-05-24T11:39:40.748512Z",
            last_modified_by: "string",
            farmer_code: "FC-ULZQLCXDXOFUG69M",
            sale_agent_code: "1234",
            id_no: "40382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254706915605",
            full_names: "Emmanuel Muchiri",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "Emmanuel Muchiri",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 0,
            phone_number_ownership_validation: 0,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 577980,
            login_attempts: 0,
            new: false,
          },
          debit: 15000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 547,
          company_id: null,
          version: 0,
          created_on: "2022-05-24T16:31:21.621469Z",
          created_by: null,
          last_modified_on: "2022-05-24T16:31:21.621469Z",
          last_modified_by: null,
          transaction_code: "PYT-FMT9VA1DZ519",
          description: null,
          farmer: {
            id: 543,
            company_id: "string",
            version: 1,
            created_on: "2022-05-24T15:36:17.868034Z",
            created_by: "string",
            last_modified_on: "2022-05-24T15:44:30.566134Z",
            last_modified_by: "string",
            farmer_code: "FC-UI4MKOBGN8WZ4FOV",
            sale_agent_code: "1234",
            id_no: "50382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254726841063",
            full_names: "Dolbert Omari",
            farmer_id: "",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 881603,
            login_attempts: 0,
            new: false,
          },
          debit: 15000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 594,
          company_id: null,
          version: 0,
          created_on: "2022-05-25T12:59:39.505854Z",
          created_by: null,
          last_modified_on: "2022-05-25T12:59:39.505854Z",
          last_modified_by: null,
          transaction_code: "PYT-GMEK9NGMIJCR",
          description: null,
          farmer: {
            id: 584,
            company_id: "string",
            version: 1,
            created_on: "2022-05-25T12:51:03.662097Z",
            created_by: "string",
            last_modified_on: "2022-05-25T12:54:35.656101Z",
            last_modified_by: "string",
            farmer_code: "FC-KVYFT5RDLLYSL9F4",
            sale_agent_code: "0024",
            id_no: "44463321",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254706199812",
            full_names: "Albert Mulei",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 855221,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 601,
          company_id: null,
          version: 0,
          created_on: "2022-05-25T14:11:13.723462Z",
          created_by: null,
          last_modified_on: "2022-05-25T14:11:13.723462Z",
          last_modified_by: null,
          transaction_code: "PYT-PE2BMQ93XTBS",
          description: null,
          farmer: {
            id: 597,
            company_id: "string",
            version: 1,
            created_on: "2022-05-25T14:08:39.293248Z",
            created_by: "string",
            last_modified_on: "2022-05-25T14:14:37.992977Z",
            last_modified_by: "string",
            farmer_code: "FC-FDHUTU16AVSKJLM0",
            sale_agent_code: "223",
            id_no: "22859213",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254723857330",
            full_names: "Roza Ngeno",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 165570,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 609,
          company_id: null,
          version: 0,
          created_on: "2022-05-25T14:18:07.896133Z",
          created_by: null,
          last_modified_on: "2022-05-25T14:18:07.896133Z",
          last_modified_by: null,
          transaction_code: "PYT-FMIMUSLOMDCJ",
          description: null,
          farmer: {
            id: 604,
            company_id: "string",
            version: 0,
            created_on: "2022-05-25T14:14:37.098367Z",
            created_by: "string",
            last_modified_on: "2022-05-25T14:14:37.098367Z",
            last_modified_by: "string",
            farmer_code: "FC-VMOISSHEEKFDENH0",
            sale_agent_code: "string",
            id_no: "22856500",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254721866245",
            full_names: "Roza Ngeno",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "PENDING_REGISTRATION",
            activation_stage: "PENDING_REGISTRATION",
            deposit_limit: 0,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 0,
            login_attempts: 0,
            new: false,
          },
          debit: 10000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 616,
          company_id: null,
          version: 0,
          created_on: "2022-05-25T17:04:06.982877Z",
          created_by: null,
          last_modified_on: "2022-05-25T17:04:06.982877Z",
          last_modified_by: null,
          transaction_code: "PYT-9CY2PLHOZXUH",
          description: null,
          farmer: {
            id: 612,
            company_id: "string",
            version: 0,
            created_on: "2022-05-25T17:00:44.042946Z",
            created_by: "string",
            last_modified_on: "2022-05-25T17:00:44.042946Z",
            last_modified_by: "string",
            farmer_code: "FC-WRYUJTZKSTWGSUVJ",
            sale_agent_code: "string",
            id_no: "60382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254735096832",
            full_names: "Valentine Wambui",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "PENDING_REGISTRATION",
            activation_stage: "PENDING_REGISTRATION",
            deposit_limit: 0,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 0,
            login_attempts: 0,
            new: false,
          },
          debit: 50000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 639,
          company_id: null,
          version: 0,
          created_on: "2022-05-27T08:16:07.276150Z",
          created_by: null,
          last_modified_on: "2022-05-27T08:16:07.276150Z",
          last_modified_by: null,
          transaction_code: "PYT-RAQLJGGLOYFR",
          description: null,
          farmer: {
            id: 634,
            company_id: "string",
            version: 1,
            created_on: "2022-05-27T08:06:16.105307Z",
            created_by: "string",
            last_modified_on: "2022-05-27T08:14:47.422291Z",
            last_modified_by: "string",
            farmer_code: "FC-BUQEWAFUJIGODJCZ",
            sale_agent_code: "1234",
            id_no: "70382477",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254712042033",
            full_names: "Kiprono Tanui",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 60467,
            login_attempts: 0,
            new: false,
          },
          debit: 40000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
        {
          id: 695,
          company_id: null,
          version: 0,
          created_on: "2022-05-29T18:12:10.181823Z",
          created_by: null,
          last_modified_on: "2022-05-29T18:12:10.181823Z",
          last_modified_by: null,
          transaction_code: "PYT-XF8WWI8DQNSK",
          description: null,
          farmer: {
            id: 667,
            company_id: "string",
            version: 1,
            created_on: "2022-05-29T17:42:45.618509Z",
            created_by: "string",
            last_modified_on: "2022-05-29T17:45:25.523275Z",
            last_modified_by: "string",
            farmer_code: "FC-G3GS9BLBFFBU2FM1",
            sale_agent_code: "1234",
            id_no: "80382478",
            county: "string",
            ward: "string",
            value_chaim: "string",
            farm_size: "string",
            photo: "string",
            signature: "string",
            additional_fields: "string",
            phone_number: "254708315062",
            full_names: "John Deng",
            farmer_id: "string",
            payment_method: "MPESA",
            account_number: "string",
            account_name: "string",
            status: "REGISTERED",
            activation_stage: "SELF_REGISTRATION",
            deposit_limit: 250000,
            loan_limit: 0,
            email_validation: 0,
            crb_validation: 0,
            phone_number_validation: 1,
            phone_number_ownership_validation: 1,
            iprs_validation: 0,
            imsi_validation: 0,
            nip: 210603,
            login_attempts: 0,
            new: false,
          },
          debit: 25000,
          credit: null,
          transaction_type: "DEPOSIT",
          account_type: "DEPOSIT_ACCOUNT",
          new: false,
        },
      ],
      pageable: {
        sort: {
          sorted: false,
          empty: true,
          unsorted: true,
        },
        page_size: 20,
        page_number: 0,
        offset: 0,
        paged: true,
        unpaged: false,
      },
      total_pages: 1,
      total_elements: 12,
      last: true,
      number: 0,
      size: 20,
      number_of_elements: 12,
      sort: {
        sorted: false,
        empty: true,
        unsorted: true,
      },
      first: true,
      empty: false,
    },
    transactions: [],
    transaction: {},
    isLoading: false,
  }),
  getters: {
    getDeposits: (state) => state.deposits,
    getTransactions: (state) => state.transactions,
    getTransaction: (state) => state.transaction,
    getLoading: (state) => state.isLoading,
  },
  actions: {
    async fetchTransactions() {
      try {
        const response = await $http.Api({
          method: "GET",
          url: "/transaction",
        });
        this.transactions = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async fetchTransaction(code: string) {
      try {
        const response = await $http.Api({
          method: "GET",
          url: `/transaction/${code}`,
        });
        this.transaction = response.data;
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },

    async updateFarmerLimits(payload) {
      try {
        const response = await $http.Api({
          method: "PUT",
          url: `/transaction/${payload.transactionNumber}`,
          data: payload.data,
        });
        console.log("updated transaction status", response.data);
      } catch (error) {
        const err = error as AxiosError;
        throw err.response;
      }
    },
  },
});
